### ISSUE TITLE
Exception at `let dic.var[:] = [1]`

### ISSUE THREAD

**Issue by Milly** [syngan/vim-vimlint#97]
Exception raised at parsing `let dic.var[:] = [1]` in `s:VimlLint.append_var()`.

`a:var.left` does not have `value` at `let v = a:var.left.value`.
(in [vimlint.vim line 417](https://github.com/syngan/vim-vimlint/blob/e5bd657693c0a67c34ad64a57e612e20019de922/autoload/vimlint.vim#L417))

#### test.vim
```vim
function Func()
  let dic = {}
  let dic.var = [1]
  let dic.var[:] = [1]
endfunction
```

#### result
```sh
$ sh /tmp/vim-vimlint/bin/vimlint.sh -u -v -l /tmp/vim-vimlint -p /tmp/vim-vimlparser test.vim
test.vim start
test.vim:::Error: EVP_0: function vimlint#vimlint[13]..<SNR>2_vimlint_file[37]..249[18]..251[1]..250[7]..249[18]..254[30]..250[7]..249[18]..258[12]..248, 行 15Vim(let):E716: 辞書型にキーが存在しません: value
```

**Comment by syngan** [comment]
I fixed it. Thanks.
