### ISSUE TITLE
`has()` show me EVL108

### ISSUE THREAD

**Issue by wsdjeg** [syngan/vim-vimlint#99]
hi @syngan , when I push code into my repo, and I see the error like this
`./config/nvim/autoload/job.vim:4:50:Error: EVL108: 1st argument of has should be a feature. see :h feature-list`
 and the line 4 is:
`let s:vim_job = !has('nvim') && has('job') && has('patch-7-4-1590')`

**Comment by hiwane** [comment]
> has('patch-7-4-1590')

use `has('patch-7.4.1590')`. see `:h feature-list` for more details.

**Comment by wsdjeg** [comment]
@hiwane thanks!
